import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

// Generated by `flutterfire configure`. Re-run if you add a new platform.
import 'firebase_options.dart';

import 'package:food_donation_app/app_router.dart';
import 'package:food_donation_app/providers/auth_provider.dart';
import 'package:food_donation_app/providers/admin_provider.dart';
import 'package:food_donation_app/providers/donation_provider.dart';
import 'package:food_donation_app/models/user_model.dart';
import 'package:food_donation_app/theme/app_theme.dart';
import 'package:food_donation_app/services/storage_service.dart';
import 'package:food_donation_app/services/donation_service.dart';
import 'package:food_donation_app/services/analytics_service.dart';

// ─────────────────────────────────────────────────────────────────────────────
//  Entry point
// ─────────────────────────────────────────────────────────────────────────────
void main() async {
  // Must be called before any Flutter framework code that interacts with the
  // platform channels (e.g., Firebase.initializeApp).
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise Firebase.
  // TODO: Replace `DefaultFirebaseOptions.currentPlatform` once you have run
  //       `flutterfire configure` and the generated `firebase_options.dart`
  //       file exists.  Until then, Firebase.initializeApp() with no options
  //       will read from google-services.json (Android) / GoogleService-Info.plist (iOS).
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const FoodBridgeApp());
}

// ─────────────────────────────────────────────────────────────────────────────
//  FoodBridgeApp
//  Root widget.  Sets up the provider tree, theme, and named routing.
// ─────────────────────────────────────────────────────────────────────────────
class FoodBridgeApp extends StatelessWidget {
  const FoodBridgeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // Services required by multiple providers
        Provider<StorageService>(create: (_) => StorageService()),
        Provider<DonationService>(create: (_) => DonationService()),

        // AuthProvider is created first; other providers may depend on it.
        ChangeNotifierProvider<AuthProvider>(
          create: (context) =>
              AuthProvider(storageService: context.read<StorageService>()),
        ),

        // AdminProvider reacts to auth changes
        ChangeNotifierProxyProvider<AuthProvider, AdminProvider>(
          create: (_) => AdminProvider(),
          update: (_, authProv, adminProv) {
            final ap = adminProv ?? AdminProvider();
            if (authProv.authState == AuthState.signedIn &&
                authProv.currentUser?.role == UserRole.admin) {
              ap.startAdminSession();
            } else {
              ap.endAdminSession();
            }
            return ap;
          },
        ),

        // DonationProvider reacts to auth changes: starts/stops Firestore
        // streams automatically when the user signs in or out.
        ChangeNotifierProxyProvider<AuthProvider, DonationProvider>(
          create: (context) => DonationProvider(
            storageService: context.read<StorageService>(),
            donationService: context.read<DonationService>(),
          ),
          update: (context, authProv, donationProv) {
            final dp =
                donationProv ??
                DonationProvider(
                  storageService: context.read<StorageService>(),
                  donationService: context.read<DonationService>(),
                );
            if (authProv.authState == AuthState.signedIn &&
                authProv.currentUser != null) {
              dp.startSessionFor(authProv.currentUser!);
            } else if (authProv.authState == AuthState.signedOut) {
              dp.endSession();
            }
            return dp;
          },
        ),
      ],
      child: MaterialApp(
        title: 'FoodBridge',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.light,

        // FirebaseAnalyticsObserver automatically logs screen_view events
        // for every named route transition — no manual calls needed.
        navigatorObservers: [AnalyticsService().observer],

        // All navigation is handled via named routes.
        // WrapperScreen (the root route) decides which screen to show
        // based on the auth state and user role.
        initialRoute: AppRouter.root,
        onGenerateRoute: AppRouter.generateRoute,
      ),
    );
  }
}
